### ISSUE TITLE
Split templated functions

### ISSUE THREAD

**Issue by okovtun** [AlexxMir81/For_loop#1]
Здравствуйте Леш! Отличная работа! То что нужно. 
templated_split не работает, потому что когда шаблонные функции делятся на файлы, то на место их вызова нужно подключать не только прототипы, но и реализации.
Попробуйте закрыть это issue через PullRequst.
И в следующий раз присылайте пожалуйста просто ссылку на репозиторий, или на проект в репозитории, еле нашел то что нужно, Вы просто в описании прислали не тот проект, и я чуть не удалил домашку))
Если будут вопросы пишите прямо сюда

**Comment by AlexxMir81** [comment]
Проект заработал, ошибка устранена.
